name: Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  buildandpush:
    uses: lsc-sde/lsc-sde/.github/workflows/docker-release.yaml@main
    with:
      imageName: dataengineering-sqlmesh-notebook
      directory: docker/dataengineering-sqlmesh-notebook
    secrets: inherit
